### ISSUE TITLE
Make admin of new repo

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/uscongress#1]
@pitkant and @dieghernan : can you please make me the admin of my new repo that I transferred so that I can access the settings button? Thank you.

**Comment by dieghernan** [comment]
Done

**Comment by stephbuon** [comment]
Thanks, @dieghernan , but I still do not see a settings button.

**Comment by dieghernan** [comment]
My bad,please try now

**Comment by stephbuon** [comment]
This worked thanks!
